### ISSUE TITLE
JCenter() alternative

### ISSUE THREAD

**Issue by vewert** [KazaKago/Cryptore#10]
Hi, I was just wondering if you have any plans to release this on Maven Central, or some other maven repository host, now that jcenter has been shut down: https://developer.android.com/studio/build/jcenter-migration.

Thank-you for your time.

**Comment by kazakago** [comment]
Hi, I have plans to migrate this library to Maven Central.
Please wait for a while until the work is completed.

**Comment by vewert** [comment]
That's great! Thanks for your prompt reply.

**Comment by kazakago** [comment]
@vewert I have released version 1.4.0 on Maven Central.
Available at `implementation com.kazakago.cryptore:cryptore:1.4.0`.
Please confirm! 🙏 

If you face problems, please open an issue.

**Comment by vewert** [comment]
I updated to 1.4.0, which is available on Maven Central, so I can now remove my dependency on jcenter()!
I did a quick test of the new version with my app and it looks fine so far, thank-you so much for your quick response to this!

**Comment by kazakago** [comment]
>  I can now remove my dependency on jcenter()!

That's great!!!!
